title:
  it: Team per la Trasformazione Digitale
  en: Digital Transformation Team
email: info@teamdigitale.governo.it
description:
  it: "Innovazione digitale per i cittadini e per lo sviluppo del Paese"
  en: "Digital innovation for citizens and for the development of the country"
index:
  it:
  en: en/index.html
url: "https://teamdigitale.governo.it"

#
# Social links
#
twitter_username:
  it: teamdigitaleIT
  en: ITdigitalteam
medium_address:
  it: https://medium.com/team-per-la-trasformazione-digitale
  en: https://medium.com/team-per-la-trasformazione-digitale/tagged/english-language
linkedin_address: https://www.linkedin.com/company/teamdigitale

# Medium posts importer
medium_archive_url: https://medium.com/team-per-la-trasformazione-digitale
medium_archive_url_eng: https://medium.com/team-per-la-trasformazione-digitale/english

# SEO
logo: /images/logo_big.png

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
exclude:
  - vendor
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - circle.yml
  - gulpfile.js
  - package.json
  
sass:
    style: compressed
